### ISSUE TITLE
Rebrand again? 😢

### ISSUE THREAD

**Issue by tarcieri** [httprb/http#241] opened 2015-07-24 03:38 UTC
I continue to receive reports from people who are confused because they try to install the "http.rb" gem which is, in fact, a completely different gem:

https://github.com/thoran/HTTP/issues/1

I've contacted the author to see if he's willing to give up the gem name. It has 1 star and ~400 downloads, all of which are probably confused people trying to install this library. It seems he is unwilling.

I'm not sure what to do. Rebranding would be the easiest way to resolve the conflict in perpetuity. However it would probably also mean changing the API, which sucks.

Is it worth it? Should we try to pick a new name, or leave it as-is?

**Comment by tarcieri** [comment] 2015-07-24 05:47
As a prospective gem name, I just registered `hypr`:

https://rubygems.org/gems/hypr

`s/HTTP/Hypr/` doesn't seem too hard? Plus at only 433,000 Google results, it seems to stand a better chance of Googlability. http.rb, by comparison, has 62,500,000

**Comment by ixti** [comment] 2015-07-24 14:44
I don't mind. I like our current name in fact - never understood names with `.lang` suffix in fact. I thought you were changing only repo's name and didn't thought that you want to change gem name too :D

But `Hypr` seems pretty nice name. Though there's `hyper` gem - but it's not HTTP client. :D
Though we should count that we have HTTP namespacing for form data for example, which twitter gem rely on.

/cc @sferik

**Comment by zanker** [comment] 2015-07-24 16:01
I'm for rebranding, just because http.rb is kind of generic and googling "http.rb" mostly brings up HTTP, Ruby code rather than http.rb (except for the first result).

Hypr is fine with me, I'm terrible at names :P

**Comment by indirect** [comment] 2015-07-24 17:13
I really like `'http'` and `HTTP`, since I can actually remember both the name and the API without any effort (utterly unlike net/http). Since the other guy chose to release after this gem, can we just take the `.rb` off of this gem's repo to remove the confusion? (I mean, I also don't have to keep explaining to confused people, so I'm not sure how much my vote counts.)

**Comment by tarcieri** [comment] 2015-07-24 17:15
@indirect that's actually what it used to be called, and I changed it to "http.rb" because the old name was ungooglable

**Comment by indirect** [comment] 2015-07-24 17:16
"The http gem"? :/ It sucks that it's ungoogleable, though. Maybe I could bribe you into continuing to release Hypr as HTTP by putting both in the release script with a gsub? :P

**Comment by tarcieri** [comment] 2015-07-24 17:17
That was actually how I tried branding it to improve the Googlability prior to changing the name to http.rb

**Comment by tarcieri** [comment] 2015-07-24 18:14
@indirect could have a shim that does something like this:

```
module HTTP; end
Hypr = HTTP
require 'hypr'
```

:wink:

**Comment by ixti** [comment] 2015-07-24 22:39
@tarcieri 

Or:

```
# file: lib/hypr.rb
require "http"
Hypr = HTTP
```

:D

**Comment by tarcieri** [comment] 2015-07-25 02:46
@sferik how do you feel about this?

**Comment by sferik** [comment] 2015-07-25 12:31
I agree, the confusion caused by the gem name not matching the repo name is a problem.

There are three possible solutions:
1. Change the gem to `http.rb`.
2. Change the repo name (back) to `http`. 
3. Change both the gem name and the repo name.

Number 1 is currently blocked by @thoran.

Number 2 may be undesirable for SEO reasons. That said, I’d be curious to see more data about whether this is actually a problem. When I search for ["ruby http library"](https://www.google.com/search?q=ruby+http+library) (in an incognito window), this library’s GitHub repo is the third result, after the Ruby Toolbox page on HTTP clients  and the official Ruby documentation for Net::HTTP. Those seem like pretty good search results to me. Given those results, I think anyone using this library ought to be able to find it. There are also various other things we could try to improve our search results without changing the name. For example, we could create GitHub Pages page (i.e. httprb.github.io) for the library that embeds Google Analytics. Then we could start collecting data about how people are finding the library: what percentage of traffic comes from direct referral versus search and what keywords people are using to find that page. By changing the repo name to `http.rb` we may done more harm than good for the sake of SEO, which might not actually be that important.

Number 3 could also do more harm than good. Changing the name will also cause a lot of confusion in the short-term while everyone switches over, as well as and potential long-term confusion with the `hyper` gem. Dropping the “e” before the “r” was cool when Flickr did it in 2004, but it feels a bit dated and overdone today. Personally, I’m attached to the name `HTTP` for the reasons @indirect stated above.

Do we really want to rename everything and create shims for the sake of SEO, which we’re not even sure is a real problem? Given the information we have today, I’d vote for option number 2 and start gathering more data. There’s a lot more to SEO than what something is named. For example, I think we could improve this library’s findability, by adding it to the [the Ruby Toolbox page on HTTP clients](https://www.ruby-toolbox.com/categories/http_clients), which is currently the top search result. Also, as this library matures and becomes more popular, our Google ranking will organically improve as more pages link to it.

**Comment by indirect** [comment] 2015-07-25 19:50
Everything Erik said.

**Comment by tarcieri** [comment] 2015-07-26 17:47
Well, with no real consensus, I think I'll just leave things as-is for now and keep hoping I can get @thoran to politely give up the `http.rb` name

**Comment by ixti** [comment] 2015-07-26 18:04
/me would like to stick with @sferik's #2 option :D

**Comment by tarcieri** [comment] 2015-07-26 18:09
Ok, I can do that. Github should redirect

**Comment by tarcieri** [comment] 2015-07-26 18:18
Renamed the repo again, and Github is redirecting

**Comment by ixti** [comment] 2015-08-25 20:08
I assume we can close this. :D

**Closed by ixti** 2015-08-25 20:08 UTC
