### ISSUE TITLE
Random OpenSSL / Headers parsing error

### ISSUE THREAD

**Issue by james-em** [httprb/http#726] opened 2022-10-19 12:48 UTC
Hi,

We have a private project that sync Shopify e-commerce with another inventory system. We have multiple shops that sync multiple times a day meaning our platform likely does over 100K of calls every day to shopify's api.

We used to use this gem until now because over the year we have been getting these kind of errors randomly

![Screen Shot 2022-10-19 at 8 46 27 AM](https://user-images.githubusercontent.com/63726983/196694744-484e17b6-7d69-490f-9bf6-d5fbb88626a1.png)

![Screen Shot 2022-10-19 at 8 36 55 AM](https://user-images.githubusercontent.com/63726983/196694745-fc2e9b16-6c0b-4198-96c1-389a7ed37c7f.png)

Usage was

```
HTTP.basic_auth(user: api_key, pass: api_password).get("url", { params: { page: 123 } })
```

I had no idea how to fix those errors even with hours of googling. I went ahead and replaced the gem with HTTParty as an attempt and to my surprise I am no longer getting random errors.

Here is a diff of my changes that fixed the error in case it helps

![Screen Shot 2022-10-19 at 8 50 37 AM](https://user-images.githubusercontent.com/63726983/196695634-bc0e8aab-5843-45dd-9dd8-67078396183d.png)

I'm leaving this here not really sure if this is of any help but I've been having those errors for at least the past year and I update all my gems monthly.

PS: I would really rather stick to HTTP.rb because of it's API. The developers have done a wonderful job at it
PS 2: The server is a Ubuntu Server 20.04 LTS and the app is running inside a Ruby 3.1.0 Docker image (using Dokku)

**Comment by tarcieri** [comment] 2022-10-19 14:25
A “TLS write client hello” error indicates the remote end is closing the socket before the client has finished sending the very first message in the TLS handshake.

This a low-level error originating in OpenSSL that can have a multitude of causes, everything from network errors to incompatible TLS configurations between client and server.

Is it sporadic? Is there an accompanying error on the server side you can share?

**Comment by james-em** [comment] 2022-10-19 14:41
> A “TLS write client hello” error indicates the remote end is closing the socket before the client has finished sending the very first message in the TLS handshake.
> 
> This a low-level error originating in OpenSSL that can have a multitude of causes, everything from network errors to incompatible TLS configurations between client and server.
> 
> Is it sporadic? Is there an accompanying error on the server side you can share?

Yes it is sporadic / random. Both exceptions are. I wish I could provide more information. All I have is the error shown above. There is no log on the Shopify side. All I can tell is that it's mostly while fetching the products (it's paginated so pulling all of them can take a lot of calls) https://shopify.dev/api/admin-rest/2022-07/resources/product#get-products

**Comment by tarcieri** [comment] 2022-10-19 15:12
The first error is happening inside OpenSSL long before any HTTP interaction takes place.

I’m not sure why it would be working with HTTParty, which is just a Net::HTTP wrapper last I checked. Perhaps it has a different OpenSSL configuration?

**Comment by james-em** [comment] 2022-10-19 18:00
> The first error is happening inside OpenSSL long before any HTTP interaction takes place.
> 
> I’m not sure why it would be working with HTTParty, which is just a Net::HTTP wrapper last I checked. Perhaps it has a different OpenSSL configuration?

I admit the comparison between `llhttp` and `Net::HTTP` is above my knowledge, I wouldn't know. All I can tell is when it comes to gem usage, I did not customize anything more than you see on the screenshot above. I believe it is safe to say i'm using the default settings when it comes to HTTP.rb and HTTParty

**Comment by tarcieri** [comment] 2022-10-19 18:17
Again, in the case of the first error, it’s occurring inside the Ruby OpenSSL extension, used by both libraries. The HTTP parser is irrelevant in that case.

**Comment by james-em** [comment] 2022-10-19 18:52
> Again, in the case of the first error, it’s occurring inside the Ruby OpenSSL extension, used by both libraries. The HTTP parser is irrelevant in that case.

Right. Then I wouldn't know because the only change I have done is the gem replacement and the diff is in the first post

**Comment by james-em** [comment] 2022-10-24 12:14
> If you can ask someone what the server-side TLS configuration is, that might be helpful

I could try asking in their forum https://community.shopify.com/c/shopify-community/ct-p/en

Is there something more specific you want me to ask?

**Comment by tarcieri** [comment] 2022-10-24 15:05
What TLS versions and ciphersuites are supported, and ideally the client-side configuration they would prefer.

As far as I can tell this is a server-side issue, although it may be impacted by the local client-side TLS configuration.

**Comment by james-em** [comment] 2022-10-25 14:33
I opened up this https://community.shopify.com/c/technical-q-a/rest-api-random-ssl-errors-and-header-parsing/m-p/1789546#M108546

**Comment by james-em** [comment] 2022-11-21 18:50
> What TLS versions and ciphersuites are supported, and ideally the client-side configuration they would prefer.
> 
> As far as I can tell this is a server-side issue, although it may be impacted by the local client-side TLS configuration.
> 
> If you can report this issue upstream somewhere, that'd be great.

We started to get randomly the same error again but this time with HTTParty

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 peeraddr=23.227.38.74:443 state=SSLv3/TLS write client hello
/app/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:46:in `connect_nonblock'
/app/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:46:in `ssl_socket_connect'
/app/vendor/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
/app/vendor/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
/app/vendor/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:965:in `start'
/app/vendor/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1530:in `request'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.20.0/lib/httparty.rb:646:in `get'
/app/lib/shopify/api.rb:65:in `next_page'
/app/lib/shopify/api.rb:59:in `get_paginated'
/app/lib/shopify/product.rb:8:in `list'
```

I guess we can close the issue since it ain't gem specific. However I wish there was something we could have done

**Comment by tarcieri** [comment] 2022-11-21 20:05
Yeah, as I said earlier this seems like a low-level OpenSSL error.

It's kind of surprising you're encountering this with Shopify though, since they're heavy Ruby users.

I'd suggest continuing to pursue it with them, especially if you can reproduce it across multiple HTTP clients.

**Closed by tarcieri** 2022-11-21 20:05 UTC

**Comment by schappim** [comment] 2023-08-23 22:04
I can confirm we are seeing the same thing sporadically with the Shopify API.
