### ISSUE TITLE
Handling EPIPE during write

### ISSUE THREAD

**Issue by milgner** [httprb/http#430] opened 2017-09-08 13:11 UTC
While trying to send a request, something happens (still investigating the source of the problem, it might be the server dropping the connection), resulting in a `EPIPE` error.
Would I be correct in assuming that this best be caught in the request writer? If so, I can prepare a PR to that effect.
Of course I'm open to other suggestions :)

```
(main)> err.backtrace
=> [
    [ 0] "<internal:prelude>:134:in `__write_nonblock'",
    [ 1] "<internal:prelude>:134:in `write_nonblock'",
    [ 2] "/app/vendor/bundle/ruby/2.3.0/gems/http-2.2.2/lib/http/timeout/per_operation.rb:77:in `block in write'",
    [ 3] "/app/vendor/bundle/ruby/2.3.0/gems/http-2.2.2/lib/http/timeout/per_operation.rb:76:in `loop'",
    [ 4] "/app/vendor/bundle/ruby/2.3.0/gems/http-2.2.2/lib/http/timeout/per_operation.rb:76:in `write'",
    [ 5] "/app/vendor/bundle/ruby/2.3.0/gems/http-2.2.2/lib/http/request/writer.rb:99:in `write'",
    [ 6] "/app/vendor/bundle/ruby/2.3.0/gems/http-2.2.2/lib/http/request/writer.rb:87:in `block in send_request'",
```

**Comment by janko-m** [comment] 2017-10-14 11:41
@milgner Yes, the `Errno::EPIPE` exception is most likely caused by the server closing the TCP connection. I would think so, because the same exception is raised when using Ruby pipes, where you try to write to the write end of the pipe while after the read end was closed.

```rb
read_pipe, write_pipe = IO.pipe
read_pipe.close
write_pipe.write("content") # Errno::EPIPE: Broken pipe
```

I think it would be appropriate to raise a `HTTP::ConnectionError` in this case, and `HTTP::Request::Writer` looks like an appropriate place to rescue that error.

@milgner It would be great if you could open a PR for this, as it confused me as well recently. I only knew what happened because I'm familiar with the `Errno::EPIPE` exception from using Ruby pipes.

**Comment by janko-m** [comment] 2017-10-14 21:38
I already opened a PR https://github.com/httprb/http/pull/436 😛

**Comment by milgner** [comment] 2017-10-15 16:14
Nice! I was afk for the weekend, thank you for the quick patch! :+1:

**Closed** 2017-10-16 20:28 UTC
