### ISSUE TITLE
Empty string instead of page content

### ISSUE THREAD

**Issue by cognita** [httprb/http#514] opened 2018-12-17 15:47 UTC
I'm trying to download a html page and I just get an empty string.

```
HTTP.get("http://stadtschreiber.ruhr/").to_s
=> ""
```
When using Net::HTTP, I get the data I am expecting:
```
Net::HTTP.get(URI("http://stadtschreiber.ruhr/"))[0..15]
=> "<!DOCTYPE html>\n"
```

http version: 4.0.0
ruby version: 2.5.3

**Comment by tarcieri** [comment] 2018-12-17 17:59
Dupe of known bug #422.

The cause is the server is sending an `Upgrade` header:

```
Upgrade: h2,h2c
```

These are presently mishandled. See open PR #489 for a potential fix.

**Closed** 2018-12-17 18:00 UTC
