### ISSUE TITLE
unable to make api request

### ISSUE THREAD

**Issue by amite** [httprb/http#382] opened 2016-12-16 16:24 UTC
I am trying to translate a curl request that works in the terminal for me into ruby code using the `http` gem.

This is the curl request that gives me back the valid json I want:

    curl -X GET --header 'Accept: application/json' --header 'api_key: somekey' --header 'authtoken: sometoken' 'https://cdn.domain.io/v3/content_types/shirts/entries?environment=dev'

With the [http gem](https://github.com/httprb/http/) I try to do this in my ruby script:

    HTTP.headers(:Accept => "application/json", :api_key => 'somekey', :authtoken => 'sometoken').get("https://cdn.domain.io/v3/content_types/shirts/entries", :params => { :environment => 'dev'}).body.readpartial

And this gives my back `"api_key":["is not valid."]}` error from the server

What am I doing wrong? How do I get this to work?

**Comment by tarcieri** [comment] 2016-12-16 16:34
I'm guessing this is probably a dupe of #337

**Comment by amite** [comment] 2016-12-16 16:38
So you are converting `_` to `-`? Changing `api_key` to `api-key` doesn't work either!? Am I reading the issue wrong? What's the solution?

**Comment by tarcieri** [comment] 2016-12-16 16:40
I don't know offhand... can you tell if the header name is getting mangled?

**Comment by amite** [comment] 2016-12-16 16:41
How do I check that? How do I read back the headers that are getting set? I tried to find a method but it didn't work!

**Comment by tarcieri** [comment] 2016-12-16 16:43
Sniff the traffic with tcpdump? Spin up a local web server and print out the whole request? Use [Burp Suite](https://portswigger.net/burp/) to MitM the connection? Add a print statement to the gem source code in `$GEM_HOME`?

**Comment by amite** [comment] 2016-12-16 17:08
I just tried doing all of the above. I don't understand any much of it I am afraid. Isn't what I am doing a standard use of the gem?

**Comment by tarcieri** [comment] 2016-12-16 17:10
Did you manage to discover if the "api_key" header is getting rewritten to something odd?

**Comment by amite** [comment] 2016-12-16 17:13
I tried doing `sudo tcpdump -n -A | grep -e 'api_key'`. Not getting any results

**Comment by amite** [comment] 2016-12-16 17:16
With `sudo tcpdump -n` I managed to capture this relevant chunk:

```
22:39:45.193278 IP 192.168.0.10.63077 > 4.2.2.2.53: 38030+ A? prod-products-contentstack-api-1083897370.us-west-2.elb.amazonaws.com. (87)
22:39:45.193787 IP 192.168.0.10.50195 > 4.2.2.2.53: 41926+ AAAA? prod-products-contentstack-api-1083897370.us-west-2.elb.amazonaws.com. (87)
```

**Comment by ixti** [comment] 2016-12-16 19:50
It's duplication of #337 for sure. `:api_key => "foobar"` willl send `Api-Key: foobar` header.
I think it really worth to make headers normalization less aggressive. I will try to come up with solution for that over this weekend.

**Comment by tarcieri** [comment] 2022-11-07 15:38
Dup of #337

**Closed by tarcieri** 2022-11-07 15:38 UTC
