### ISSUE TITLE
Nested URI params for GET requests not constructed properly

### ISSUE THREAD

**Issue by michaelherold** [httprb/http#259] opened 2015-09-10 16:59 UTC
Per @ixti's [request](https://groups.google.com/d/msg/httprb/g6pxli0tTyw/HyesRJCcAQAJ):

I'm using http.rb in a library and experiencing some unexpected behavior. Here's a spec of what I expected to happen (written for [client_spec.rb on master as of today](https://github.com/httprb/http/blob/7869ff2ba20d46ceec5e2f22058be3b74b433150/spec/lib/http/client_spec.rb)):

``` ruby
it "properly encodes nested params" do
  expect(HTTP::Request).to receive(:new) do |_, uri|
    expect(uri.query).to eq "foo%5Bbar%5D%3Dtest" # e.g. foo[bar]=test
  end

  client.get("http://example.com/", :params => {:foo => {:bar => "test"}})
end
```

And its result:

```
1) HTTP::Client parsing params properly encodes nested params
   Failure/Error: expect(uri.query).to eq "foo%5Bbar%5D%3Dtest"

     expected: "foo%5Bbar%5D%3Dtest"
          got: "foo=%7B%3Abar%3D%3E%22test%22%7D"  # e.g. "foo={:bar => \"test\"}"

     (compared using ==)
```

Digging into the code, I found that this method is essentially a delegate to Addressable::URI.form_encode.

I'm wondering: is this intended behavior within the scope of http.rb? I'm not terribly familiar with the RFCs around URI parsing, but my understanding was that a hash/dictionary/map-like structure would be represented as "top_key[key]=value", which is what I was anticipating.

**Comment by tarcieri** [comment] 2015-09-10 18:34
It looks like the main implementation of this is in ActiveSupport:

http://apidock.com/rails/ActiveSupport/CoreExtensions/Hash/to_query

I'm not really a big fan of pulling in ActiveSupport. I was reading that Addressable used to support this, but it got removed?

**Comment by ixti** [comment] 2015-09-10 18:49
I was going to add that as part of form data gem in fact.
Not gonna pull in ActiveSupport.

**Comment by tarcieri** [comment] 2015-09-10 19:04
Sounds good @ixti

**Comment by tarcieri** [comment] 2015-12-13 01:52
@ixti do you have time to work on this for 1.0, or should we fix it in 1.1+?

**Comment by ixti** [comment] 2015-12-13 14:43
Not sure I will be able to fix this today, so if it will not happen in 1.0 - it's ok to push that to 1.1 I think

**Comment by janko-m** [comment] 2018-11-18 08:49
@tarcieri @ixti This issues seems to be the same as https://github.com/httprb/http/issues/259. Should we close one of these?

**Comment by janko-m** [comment] 2018-11-18 14:34
Oops, thanks for the heads up, I meant this one: https://github.com/httprb/http/issues/428

**Comment by ixti** [comment] 2018-11-18 21:43
Yeah. This is a duplicate of #428 for sure. Although in fact #428 is duplicate of this but considering that latter one contains more comments and proposed solutions I'm closing this issue. Thanks for catching this!

**Closed by ixti** 2018-11-18 21:43 UTC
Labels: Bug, Improvement
